name       : arp-scan
version    : 1.9
release    : 1
source     :
    - git|https://github.com/royhills/arp-scan : af4a1a26b9a1f39b2c447a5a9b96ab37bae52f32
license    : GPL-3.0
component  : system.util
summary    : ARP scanner for local networks
description: |
    A tool that uses ARP to discover and fingerprint IP hosts on the local network
builddeps  :
    - libpcap-devel
rundeps    :
    - libpcap
    - libwww-perl
setup      : |
    %reconfigure
build      : |
    %make
check      : |
    %make check
install    : |
    %make_install
