name       : nautilus-share
version    : 0.7.3
release    : 1
source     :
    - git|https://github.com/GNOME/nautilus-share : 201af392b3acf9962a4a8a2d55afb10ae0d4b526
license    : GPL-2.0
component  : desktop.gnome
summary    : Nautilus extension to share folder using Samba
description: |
    Nautilus extension to share folder using Samba
builddeps  :
    - pkgconfig(smbclient)
    - nautilus-extension-devel
    - intltool
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
