name       : libfakekey
version    : 0.1
release    : 1
source     :
    - https://downloads.yoctoproject.org/releases/matchbox/libfakekey/0.1/libfakekey-0.1.tar.gz : 33f55905d6680aa4fba7c5c5809ae16a4220d827ddb655d7afb08c623dbdba82
license    : GPL-2.0
component  : xorg.library
summary    : X virtual keyboard library
description: |
    X virtual keyboard library for converting characters into X server key presses
builddeps  :
    - pkgconfig(xtst)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
