name       : wds
version    : 1.1.0
release    : 1
source     :
    - https://github.com/01org/wds/archive/v1.1.0.tar.gz : 6c3f11f1ce130d388047b456647b229c452cce72c6e13a4f2288f1f89d51250f
license    : LGPL-2.1
component  : xorg.display
summary    : Wireless Display Software For Linux OS (WDS)
description: |
    WDS is a set of libraries for developers who want to build Wi-Fi Display applications on linux.
builddeps  :
    - pkgconfig(gstreamer-1.0)
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
