name       : kdeconnect
version    : 1.0.3
release    : 1
source     :
    - https://github.com/KDE/kdeconnect-kde/archive/v1.0.3.tar.gz : 5d0bb392926c4387ef556ab5569efe029d14c1227513b4e073b77415b815d6c7
license    : GPL-2.0
component  : desktop.kde
summary    : KDE Connect adds communication between KDE and your smartphone.
description: |
    KDE Connect is a multi-platform app that allows your devices to communicate (eg: your phone and your computer).
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xtst)
    - extra-cmake-modules
    - kcmutils-devel
    - kconfigwidgets-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - kwayland-devel
    - libfakekey-devel
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
