name       : picocom
version    : 2.2
release    : 1
source     :
    - https://github.com/npat-efault/picocom/archive/2.2.tar.gz : 3e3904158d675541f0fcfdcd1f671b38445338f536080f5de8d6674b5f33d4ce
license    : GPL-2.0
component  : system.utils
summary    : Dumb-terminal emulator for serial connections
description: |
    Dumb terminal emulator for serial simple, manual, modem configuration, testing, and debugging tool. 
    It has also served (quite well) as a low-tech serial communications program to allow access to all 
    types of devices that provide serial consoles. It could also prove useful in many other similar tasks.
build      : |
    %make
install    : |
    install -Dm00755 picocom $installdir/usr/bin/picocom
    install -Dm00644 picocom.1 $installdir/usr/share/man/man1/picocom.1
