name       : python-requests-oauthlib
version    : 0.8.0
release    : 1
source     :
    - https://github.com/requests/requests-oauthlib/archive/v0.8.0.tar.gz : 96780c7bf963b6f8ce13aa685e0d3bdc12dfc4877c2107021b255095794befa1
license    : ISC
component  : programming.python
summary    : OAuthlib support for Python-Requests
description: |
    This project provides first-class OAuth library support for python-requests.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
rundeps    :
    - python-requests
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install

